name: app
description: Email helper app for quick replies and drafts.
publish_to: "none"

version: 1.0.3+4

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  share_plus: ^11.0.0
  shared_preferences: ^2.2.3
  google_mlkit_text_recognition: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon.png"
